# Generated by Django 2.1.8 on 2019-05-18 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_scannedplant_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scannedplant',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
