# Generated by Django 2.1.8 on 2019-05-18 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20190518_1427'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scannedplant',
            old_name='plant_name',
            new_name='name',
        ),
    ]
