# Generated by Django 2.1.8 on 2019-05-18 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20190518_1444'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialPlant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('type', models.CharField(choices=[('IN', 'invasive'), ('ZA', 'protected')], max_length=2)),
            ],
        ),
    ]
